<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AdvancedAds\\InFeed\\Admin\\Placement_Settings' => $baseDir . '/includes/admin/class-placement-settings.php',
    'AdvancedAds\\InFeed\\Autoloader' => $baseDir . '/includes/class-autoloader.php',
    'AdvancedAds\\InFeed\\Bootstrap' => $baseDir . '/includes/class-bootstrap.php',
    'AdvancedAds\\InFeed\\Frontend' => $baseDir . '/includes/class-frontend.php',
    'AdvancedAds\\InFeed\\In_Feed_Placement' => $baseDir . '/includes/class-in-feed-placement.php',
    'AdvancedAds\\InFeed\\In_Feed_Type' => $baseDir . '/includes/class-in-feed-type.php',
    'AdvancedAds\\InFeed\\Placement_Types' => $baseDir . '/includes/class-placement-types.php',
    'AdvancedAds\\InFeed\\Plugin' => $baseDir . '/includes/class-plugin.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
