<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitda28c014fde7f21617dc1fdd1dfa95c9
{
    public static $classMap = array (
        'AdvancedAds\\InFeed\\Admin\\Placement_Settings' => __DIR__ . '/../..' . '/includes/admin/class-placement-settings.php',
        'AdvancedAds\\InFeed\\Autoloader' => __DIR__ . '/../..' . '/includes/class-autoloader.php',
        'AdvancedAds\\InFeed\\Bootstrap' => __DIR__ . '/../..' . '/includes/class-bootstrap.php',
        'AdvancedAds\\InFeed\\Frontend' => __DIR__ . '/../..' . '/includes/class-frontend.php',
        'AdvancedAds\\InFeed\\In_Feed_Placement' => __DIR__ . '/../..' . '/includes/class-in-feed-placement.php',
        'AdvancedAds\\InFeed\\In_Feed_Type' => __DIR__ . '/../..' . '/includes/class-in-feed-type.php',
        'AdvancedAds\\InFeed\\Placement_Types' => __DIR__ . '/../..' . '/includes/class-placement-types.php',
        'AdvancedAds\\InFeed\\Plugin' => __DIR__ . '/../..' . '/includes/class-plugin.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInitda28c014fde7f21617dc1fdd1dfa95c9::$classMap;

        }, null, ClassLoader::class);
    }
}
